name: stu
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  app_links: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  vibration: ^3.1.3
  stop_watch_timer: ^3.2.1
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  supabase_flutter: ^2.9.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/GitHub_Invertocat_Light.png
